/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockaudio.h"

static const char* CMockString_audio_init = "audio_init";
static const char* CMockString_audio_is_playing = "audio_is_playing";
static const char* CMockString_audio_reset = "audio_reset";
static const char* CMockString_audio_shutdown = "audio_shutdown";
static const char* CMockString_audio_start_bgm = "audio_start_bgm";
static const char* CMockString_audio_start_sfx = "audio_start_sfx";
static const char* CMockString_audio_stop_bgm = "audio_stop_bgm";
static const char* CMockString_audio_stop_sfx = "audio_stop_sfx";
static const char* CMockString_bgm_name = "bgm_name";
static const char* CMockString_sfx_name = "sfx_name";

typedef struct _CMOCK_audio_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_audio_init_CALL_INSTANCE;

typedef struct _CMOCK_audio_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_audio_reset_CALL_INSTANCE;

typedef struct _CMOCK_audio_shutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_audio_shutdown_CALL_INSTANCE;

typedef struct _CMOCK_audio_start_bgm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_bgm_name;

} CMOCK_audio_start_bgm_CALL_INSTANCE;

typedef struct _CMOCK_audio_stop_bgm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_audio_stop_bgm_CALL_INSTANCE;

typedef struct _CMOCK_audio_start_sfx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_sfx_name;

} CMOCK_audio_start_sfx_CALL_INSTANCE;

typedef struct _CMOCK_audio_stop_sfx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_audio_stop_sfx_CALL_INSTANCE;

typedef struct _CMOCK_audio_is_playing_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_audio_is_playing_CALL_INSTANCE;

static struct MockaudioInstance
{
  CMOCK_MEM_INDEX_TYPE audio_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_reset_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_shutdown_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_start_bgm_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_stop_bgm_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_start_sfx_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_stop_sfx_CallInstance;
  CMOCK_MEM_INDEX_TYPE audio_is_playing_CallInstance;
} Mock;


void Mockaudio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.audio_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_reset_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_shutdown_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_shutdown);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_start_bgm_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_start_bgm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_stop_bgm_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_stop_bgm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_start_sfx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_start_sfx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_stop_sfx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_stop_sfx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.audio_is_playing_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_audio_is_playing);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockaudio_Init(void)
{
  Mockaudio_Destroy();
}

void Mockaudio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void audio_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_init);
  cmock_call_instance = (CMOCK_audio_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_init_CallInstance);
  Mock.audio_init_CallInstance = CMock_Guts_MemNext(Mock.audio_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void audio_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_init_CALL_INSTANCE));
  CMOCK_audio_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_init_CallInstance = CMock_Guts_MemChain(Mock.audio_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void audio_reset(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_reset);
  cmock_call_instance = (CMOCK_audio_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_reset_CallInstance);
  Mock.audio_reset_CallInstance = CMock_Guts_MemNext(Mock.audio_reset_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void audio_reset_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_reset_CALL_INSTANCE));
  CMOCK_audio_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_reset_CallInstance = CMock_Guts_MemChain(Mock.audio_reset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void audio_shutdown(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_shutdown_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_shutdown);
  cmock_call_instance = (CMOCK_audio_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_shutdown_CallInstance);
  Mock.audio_shutdown_CallInstance = CMock_Guts_MemNext(Mock.audio_shutdown_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void audio_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_shutdown_CALL_INSTANCE));
  CMOCK_audio_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_shutdown_CallInstance = CMock_Guts_MemChain(Mock.audio_shutdown_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

int audio_start_bgm(const char* bgm_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_start_bgm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_start_bgm);
  cmock_call_instance = (CMOCK_audio_start_bgm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_start_bgm_CallInstance);
  Mock.audio_start_bgm_CallInstance = CMock_Guts_MemNext(Mock.audio_start_bgm_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_audio_start_bgm,CMockString_bgm_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_bgm_name, bgm_name, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_audio_start_bgm(CMOCK_audio_start_bgm_CALL_INSTANCE* cmock_call_instance, const char* bgm_name);
void CMockExpectParameters_audio_start_bgm(CMOCK_audio_start_bgm_CALL_INSTANCE* cmock_call_instance, const char* bgm_name)
{
  cmock_call_instance->Expected_bgm_name = bgm_name;
}

void audio_start_bgm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* bgm_name, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_start_bgm_CALL_INSTANCE));
  CMOCK_audio_start_bgm_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_start_bgm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_start_bgm_CallInstance = CMock_Guts_MemChain(Mock.audio_start_bgm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_audio_start_bgm(cmock_call_instance, bgm_name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void audio_stop_bgm(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_stop_bgm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_stop_bgm);
  cmock_call_instance = (CMOCK_audio_stop_bgm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_stop_bgm_CallInstance);
  Mock.audio_stop_bgm_CallInstance = CMock_Guts_MemNext(Mock.audio_stop_bgm_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void audio_stop_bgm_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_stop_bgm_CALL_INSTANCE));
  CMOCK_audio_stop_bgm_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_stop_bgm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_stop_bgm_CallInstance = CMock_Guts_MemChain(Mock.audio_stop_bgm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

int audio_start_sfx(const char* sfx_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_start_sfx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_start_sfx);
  cmock_call_instance = (CMOCK_audio_start_sfx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_start_sfx_CallInstance);
  Mock.audio_start_sfx_CallInstance = CMock_Guts_MemNext(Mock.audio_start_sfx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_audio_start_sfx,CMockString_sfx_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_sfx_name, sfx_name, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_audio_start_sfx(CMOCK_audio_start_sfx_CALL_INSTANCE* cmock_call_instance, const char* sfx_name);
void CMockExpectParameters_audio_start_sfx(CMOCK_audio_start_sfx_CALL_INSTANCE* cmock_call_instance, const char* sfx_name)
{
  cmock_call_instance->Expected_sfx_name = sfx_name;
}

void audio_start_sfx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* sfx_name, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_start_sfx_CALL_INSTANCE));
  CMOCK_audio_start_sfx_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_start_sfx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_start_sfx_CallInstance = CMock_Guts_MemChain(Mock.audio_start_sfx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_audio_start_sfx(cmock_call_instance, sfx_name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void audio_stop_sfx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_stop_sfx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_stop_sfx);
  cmock_call_instance = (CMOCK_audio_stop_sfx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_stop_sfx_CallInstance);
  Mock.audio_stop_sfx_CallInstance = CMock_Guts_MemNext(Mock.audio_stop_sfx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void audio_stop_sfx_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_stop_sfx_CALL_INSTANCE));
  CMOCK_audio_stop_sfx_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_stop_sfx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_stop_sfx_CallInstance = CMock_Guts_MemChain(Mock.audio_stop_sfx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

bool audio_is_playing(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_audio_is_playing_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_audio_is_playing);
  cmock_call_instance = (CMOCK_audio_is_playing_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.audio_is_playing_CallInstance);
  Mock.audio_is_playing_CallInstance = CMock_Guts_MemNext(Mock.audio_is_playing_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void audio_is_playing_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_audio_is_playing_CALL_INSTANCE));
  CMOCK_audio_is_playing_CALL_INSTANCE* cmock_call_instance = (CMOCK_audio_is_playing_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.audio_is_playing_CallInstance = CMock_Guts_MemChain(Mock.audio_is_playing_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

