/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKAUDIO_H
#define _MOCKAUDIO_H

#include "unity.h"
#include "audio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockaudio_Init(void);
void Mockaudio_Destroy(void);
void Mockaudio_Verify(void);




#define audio_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("audio_init requires _Expect (not AndReturn)");
#define audio_init_Expect() audio_init_CMockExpect(__LINE__)
void audio_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define audio_reset_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("audio_reset requires _Expect (not AndReturn)");
#define audio_reset_Expect() audio_reset_CMockExpect(__LINE__)
void audio_reset_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define audio_shutdown_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("audio_shutdown requires _Expect (not AndReturn)");
#define audio_shutdown_Expect() audio_shutdown_CMockExpect(__LINE__)
void audio_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define audio_start_bgm_Expect(bgm_name) TEST_FAIL_MESSAGE("audio_start_bgm requires _ExpectAndReturn");
#define audio_start_bgm_ExpectAndReturn(bgm_name, cmock_retval) audio_start_bgm_CMockExpectAndReturn(__LINE__, bgm_name, cmock_retval)
void audio_start_bgm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* bgm_name, int cmock_to_return);
#define audio_stop_bgm_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("audio_stop_bgm requires _Expect (not AndReturn)");
#define audio_stop_bgm_Expect() audio_stop_bgm_CMockExpect(__LINE__)
void audio_stop_bgm_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define audio_start_sfx_Expect(sfx_name) TEST_FAIL_MESSAGE("audio_start_sfx requires _ExpectAndReturn");
#define audio_start_sfx_ExpectAndReturn(sfx_name, cmock_retval) audio_start_sfx_CMockExpectAndReturn(__LINE__, sfx_name, cmock_retval)
void audio_start_sfx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* sfx_name, int cmock_to_return);
#define audio_stop_sfx_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("audio_stop_sfx requires _Expect (not AndReturn)");
#define audio_stop_sfx_Expect() audio_stop_sfx_CMockExpect(__LINE__)
void audio_stop_sfx_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define audio_is_playing_Expect() TEST_FAIL_MESSAGE("audio_is_playing requires _ExpectAndReturn");
#define audio_is_playing_ExpectAndReturn(cmock_retval) audio_is_playing_CMockExpectAndReturn(__LINE__, cmock_retval)
void audio_is_playing_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
