/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktext.h"

static const char* CMockString_speaker = "speaker";
static const char* CMockString_text = "text";
static const char* CMockString_text_begin_dialogue = "text_begin_dialogue";
static const char* CMockString_text_begin_narration = "text_begin_narration";
static const char* CMockString_text_clear = "text_clear";
static const char* CMockString_text_debug_clear = "text_debug_clear";
static const char* CMockString_text_debug_set = "text_debug_set";
static const char* CMockString_text_finish_immediately = "text_finish_immediately";
static const char* CMockString_text_init = "text_init";
static const char* CMockString_text_is_finished = "text_is_finished";
static const char* CMockString_text_update = "text_update";

typedef struct _CMOCK_text_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_text_init_CALL_INSTANCE;

typedef struct _CMOCK_text_clear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_text_clear_CALL_INSTANCE;

typedef struct _CMOCK_text_begin_dialogue_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_speaker;
  const char* Expected_text;

} CMOCK_text_begin_dialogue_CALL_INSTANCE;

typedef struct _CMOCK_text_begin_narration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_text;

} CMOCK_text_begin_narration_CALL_INSTANCE;

typedef struct _CMOCK_text_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_text_update_CALL_INSTANCE;

typedef struct _CMOCK_text_finish_immediately_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_text_finish_immediately_CALL_INSTANCE;

typedef struct _CMOCK_text_is_finished_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_text_is_finished_CALL_INSTANCE;

typedef struct _CMOCK_text_debug_set_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_text;

} CMOCK_text_debug_set_CALL_INSTANCE;

typedef struct _CMOCK_text_debug_clear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_text_debug_clear_CALL_INSTANCE;

static struct MocktextInstance
{
  CMOCK_MEM_INDEX_TYPE text_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_clear_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_begin_dialogue_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_begin_narration_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_update_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_finish_immediately_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_is_finished_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_debug_set_CallInstance;
  CMOCK_MEM_INDEX_TYPE text_debug_clear_CallInstance;
} Mock;


void Mocktext_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.text_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_clear_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_clear);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_begin_dialogue_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_begin_dialogue);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_begin_narration_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_begin_narration);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_update_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_finish_immediately_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_finish_immediately);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_is_finished_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_is_finished);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_debug_set_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_debug_set);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.text_debug_clear_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_text_debug_clear);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktext_Init(void)
{
  Mocktext_Destroy();
}

void Mocktext_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void text_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_init);
  cmock_call_instance = (CMOCK_text_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_init_CallInstance);
  Mock.text_init_CallInstance = CMock_Guts_MemNext(Mock.text_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void text_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_init_CALL_INSTANCE));
  CMOCK_text_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_init_CallInstance = CMock_Guts_MemChain(Mock.text_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void text_clear(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_clear_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_clear);
  cmock_call_instance = (CMOCK_text_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_clear_CallInstance);
  Mock.text_clear_CallInstance = CMock_Guts_MemNext(Mock.text_clear_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void text_clear_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_clear_CALL_INSTANCE));
  CMOCK_text_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_clear_CallInstance = CMock_Guts_MemChain(Mock.text_clear_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void text_begin_dialogue(const char* speaker, const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_begin_dialogue_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_begin_dialogue);
  cmock_call_instance = (CMOCK_text_begin_dialogue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_begin_dialogue_CallInstance);
  Mock.text_begin_dialogue_CallInstance = CMock_Guts_MemNext(Mock.text_begin_dialogue_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_text_begin_dialogue,CMockString_speaker);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_speaker, speaker, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_text_begin_dialogue,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_text_begin_dialogue(CMOCK_text_begin_dialogue_CALL_INSTANCE* cmock_call_instance, const char* speaker, const char* text);
void CMockExpectParameters_text_begin_dialogue(CMOCK_text_begin_dialogue_CALL_INSTANCE* cmock_call_instance, const char* speaker, const char* text)
{
  cmock_call_instance->Expected_speaker = speaker;
  cmock_call_instance->Expected_text = text;
}

void text_begin_dialogue_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* speaker, const char* text)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_begin_dialogue_CALL_INSTANCE));
  CMOCK_text_begin_dialogue_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_begin_dialogue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_begin_dialogue_CallInstance = CMock_Guts_MemChain(Mock.text_begin_dialogue_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_text_begin_dialogue(cmock_call_instance, speaker, text);
}

void text_begin_narration(const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_begin_narration_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_begin_narration);
  cmock_call_instance = (CMOCK_text_begin_narration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_begin_narration_CallInstance);
  Mock.text_begin_narration_CallInstance = CMock_Guts_MemNext(Mock.text_begin_narration_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_text_begin_narration,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_text_begin_narration(CMOCK_text_begin_narration_CALL_INSTANCE* cmock_call_instance, const char* text);
void CMockExpectParameters_text_begin_narration(CMOCK_text_begin_narration_CALL_INSTANCE* cmock_call_instance, const char* text)
{
  cmock_call_instance->Expected_text = text;
}

void text_begin_narration_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* text)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_begin_narration_CALL_INSTANCE));
  CMOCK_text_begin_narration_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_begin_narration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_begin_narration_CallInstance = CMock_Guts_MemChain(Mock.text_begin_narration_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_text_begin_narration(cmock_call_instance, text);
}

void text_update(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_update);
  cmock_call_instance = (CMOCK_text_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_update_CallInstance);
  Mock.text_update_CallInstance = CMock_Guts_MemNext(Mock.text_update_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void text_update_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_update_CALL_INSTANCE));
  CMOCK_text_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_update_CallInstance = CMock_Guts_MemChain(Mock.text_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void text_finish_immediately(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_finish_immediately_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_finish_immediately);
  cmock_call_instance = (CMOCK_text_finish_immediately_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_finish_immediately_CallInstance);
  Mock.text_finish_immediately_CallInstance = CMock_Guts_MemNext(Mock.text_finish_immediately_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void text_finish_immediately_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_finish_immediately_CALL_INSTANCE));
  CMOCK_text_finish_immediately_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_finish_immediately_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_finish_immediately_CallInstance = CMock_Guts_MemChain(Mock.text_finish_immediately_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

bool text_is_finished(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_is_finished_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_is_finished);
  cmock_call_instance = (CMOCK_text_is_finished_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_is_finished_CallInstance);
  Mock.text_is_finished_CallInstance = CMock_Guts_MemNext(Mock.text_is_finished_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void text_is_finished_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_is_finished_CALL_INSTANCE));
  CMOCK_text_is_finished_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_is_finished_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_is_finished_CallInstance = CMock_Guts_MemChain(Mock.text_is_finished_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void text_debug_set(const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_debug_set_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_debug_set);
  cmock_call_instance = (CMOCK_text_debug_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_debug_set_CallInstance);
  Mock.text_debug_set_CallInstance = CMock_Guts_MemNext(Mock.text_debug_set_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_text_debug_set,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_text_debug_set(CMOCK_text_debug_set_CALL_INSTANCE* cmock_call_instance, const char* text);
void CMockExpectParameters_text_debug_set(CMOCK_text_debug_set_CALL_INSTANCE* cmock_call_instance, const char* text)
{
  cmock_call_instance->Expected_text = text;
}

void text_debug_set_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* text)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_debug_set_CALL_INSTANCE));
  CMOCK_text_debug_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_debug_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_debug_set_CallInstance = CMock_Guts_MemChain(Mock.text_debug_set_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_text_debug_set(cmock_call_instance, text);
}

void text_debug_clear(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_text_debug_clear_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_text_debug_clear);
  cmock_call_instance = (CMOCK_text_debug_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.text_debug_clear_CallInstance);
  Mock.text_debug_clear_CallInstance = CMock_Guts_MemNext(Mock.text_debug_clear_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void text_debug_clear_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_text_debug_clear_CALL_INSTANCE));
  CMOCK_text_debug_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_text_debug_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.text_debug_clear_CallInstance = CMock_Guts_MemChain(Mock.text_debug_clear_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

