/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSCRIPT_H
#define _MOCKSCRIPT_H

#include "unity.h"
#include "script.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockscript_Init(void);
void Mockscript_Destroy(void);
void Mockscript_Verify(void);




#define script_open_Expect(scene_name) TEST_FAIL_MESSAGE("script_open requires _ExpectAndReturn");
#define script_open_ExpectAndReturn(scene_name, cmock_retval) script_open_CMockExpectAndReturn(__LINE__, scene_name, cmock_retval)
void script_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* scene_name, int cmock_to_return);
#define script_close_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("script_close requires _Expect (not AndReturn)");
#define script_close_Expect() script_close_CMockExpect(__LINE__)
void script_close_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define script_read_line_Expect(out_line, out_size) TEST_FAIL_MESSAGE("script_read_line requires _ExpectAndReturn");
#define script_read_line_ExpectAndReturn(out_line, out_size, cmock_retval) script_read_line_CMockExpectAndReturn(__LINE__, out_line, out_size, cmock_retval)
void script_read_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* out_line, size_t out_size, ScriptResult cmock_to_return);
#define script_is_open_Expect() TEST_FAIL_MESSAGE("script_is_open requires _ExpectAndReturn");
#define script_is_open_ExpectAndReturn(cmock_retval) script_is_open_CMockExpectAndReturn(__LINE__, cmock_retval)
void script_is_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define script_current_line_Expect() TEST_FAIL_MESSAGE("script_current_line requires _ExpectAndReturn");
#define script_current_line_ExpectAndReturn(cmock_retval) script_current_line_CMockExpectAndReturn(__LINE__, cmock_retval)
void script_current_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define script_current_script_Expect(out, out_size) TEST_FAIL_MESSAGE("script_current_script requires _ExpectAndReturn");
#define script_current_script_ExpectAndReturn(out, out_size, cmock_retval) script_current_script_CMockExpectAndReturn(__LINE__, out, out_size, cmock_retval)
void script_current_script_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* out, size_t out_size, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
