/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockscript.h"

static const char* CMockString_out = "out";
static const char* CMockString_out_line = "out_line";
static const char* CMockString_out_size = "out_size";
static const char* CMockString_scene_name = "scene_name";
static const char* CMockString_script_close = "script_close";
static const char* CMockString_script_current_line = "script_current_line";
static const char* CMockString_script_current_script = "script_current_script";
static const char* CMockString_script_is_open = "script_is_open";
static const char* CMockString_script_open = "script_open";
static const char* CMockString_script_read_line = "script_read_line";

typedef struct _CMOCK_script_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_scene_name;

} CMOCK_script_open_CALL_INSTANCE;

typedef struct _CMOCK_script_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_script_close_CALL_INSTANCE;

typedef struct _CMOCK_script_read_line_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ScriptResult ReturnVal;
  char* Expected_out_line;
  size_t Expected_out_size;

} CMOCK_script_read_line_CALL_INSTANCE;

typedef struct _CMOCK_script_is_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_script_is_open_CALL_INSTANCE;

typedef struct _CMOCK_script_current_line_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_script_current_line_CALL_INSTANCE;

typedef struct _CMOCK_script_current_script_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_out;
  size_t Expected_out_size;

} CMOCK_script_current_script_CALL_INSTANCE;

static struct MockscriptInstance
{
  CMOCK_MEM_INDEX_TYPE script_open_CallInstance;
  CMOCK_MEM_INDEX_TYPE script_close_CallInstance;
  CMOCK_MEM_INDEX_TYPE script_read_line_CallInstance;
  CMOCK_MEM_INDEX_TYPE script_is_open_CallInstance;
  CMOCK_MEM_INDEX_TYPE script_current_line_CallInstance;
  CMOCK_MEM_INDEX_TYPE script_current_script_CallInstance;
} Mock;


void Mockscript_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.script_open_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.script_close_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_close);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.script_read_line_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_read_line);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.script_is_open_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_is_open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.script_current_line_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_current_line);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.script_current_script_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_script_current_script);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockscript_Init(void)
{
  Mockscript_Destroy();
}

void Mockscript_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int script_open(const char* scene_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_open);
  cmock_call_instance = (CMOCK_script_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_open_CallInstance);
  Mock.script_open_CallInstance = CMock_Guts_MemNext(Mock.script_open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_script_open,CMockString_scene_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_scene_name, scene_name, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_script_open(CMOCK_script_open_CALL_INSTANCE* cmock_call_instance, const char* scene_name);
void CMockExpectParameters_script_open(CMOCK_script_open_CALL_INSTANCE* cmock_call_instance, const char* scene_name)
{
  cmock_call_instance->Expected_scene_name = scene_name;
}

void script_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* scene_name, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_open_CALL_INSTANCE));
  CMOCK_script_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_open_CallInstance = CMock_Guts_MemChain(Mock.script_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_script_open(cmock_call_instance, scene_name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void script_close(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_close);
  cmock_call_instance = (CMOCK_script_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_close_CallInstance);
  Mock.script_close_CallInstance = CMock_Guts_MemNext(Mock.script_close_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void script_close_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_close_CALL_INSTANCE));
  CMOCK_script_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_close_CallInstance = CMock_Guts_MemChain(Mock.script_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

ScriptResult script_read_line(char* out_line, size_t out_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_read_line_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_read_line);
  cmock_call_instance = (CMOCK_script_read_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_read_line_CallInstance);
  Mock.script_read_line_CallInstance = CMock_Guts_MemNext(Mock.script_read_line_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_script_read_line,CMockString_out_line);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_out_line, out_line, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_script_read_line,CMockString_out_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_out_size, &out_size, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_script_read_line(CMOCK_script_read_line_CALL_INSTANCE* cmock_call_instance, char* out_line, size_t out_size);
void CMockExpectParameters_script_read_line(CMOCK_script_read_line_CALL_INSTANCE* cmock_call_instance, char* out_line, size_t out_size)
{
  cmock_call_instance->Expected_out_line = out_line;
  memcpy((void*)(&cmock_call_instance->Expected_out_size), (const void*)(&out_size),
         sizeof(size_t[sizeof(out_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void script_read_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* out_line, size_t out_size, ScriptResult cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_read_line_CALL_INSTANCE));
  CMOCK_script_read_line_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_read_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_read_line_CallInstance = CMock_Guts_MemChain(Mock.script_read_line_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_script_read_line(cmock_call_instance, out_line, out_size);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(ScriptResult[sizeof(cmock_to_return) == sizeof(ScriptResult) ? 1 : -1])); /* add ScriptResult to :treat_as_array if this causes an error */
}

bool script_is_open(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_is_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_is_open);
  cmock_call_instance = (CMOCK_script_is_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_is_open_CallInstance);
  Mock.script_is_open_CallInstance = CMock_Guts_MemNext(Mock.script_is_open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void script_is_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_is_open_CALL_INSTANCE));
  CMOCK_script_is_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_is_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_is_open_CallInstance = CMock_Guts_MemChain(Mock.script_is_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int script_current_line(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_current_line_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_current_line);
  cmock_call_instance = (CMOCK_script_current_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_current_line_CallInstance);
  Mock.script_current_line_CallInstance = CMock_Guts_MemNext(Mock.script_current_line_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void script_current_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_current_line_CALL_INSTANCE));
  CMOCK_script_current_line_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_current_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_current_line_CallInstance = CMock_Guts_MemChain(Mock.script_current_line_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int script_current_script(char* out, size_t out_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_script_current_script_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_script_current_script);
  cmock_call_instance = (CMOCK_script_current_script_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.script_current_script_CallInstance);
  Mock.script_current_script_CallInstance = CMock_Guts_MemNext(Mock.script_current_script_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_script_current_script,CMockString_out);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_out, out, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_script_current_script,CMockString_out_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_out_size, &out_size, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_script_current_script(CMOCK_script_current_script_CALL_INSTANCE* cmock_call_instance, char* out, size_t out_size);
void CMockExpectParameters_script_current_script(CMOCK_script_current_script_CALL_INSTANCE* cmock_call_instance, char* out, size_t out_size)
{
  cmock_call_instance->Expected_out = out;
  memcpy((void*)(&cmock_call_instance->Expected_out_size), (const void*)(&out_size),
         sizeof(size_t[sizeof(out_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void script_current_script_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* out, size_t out_size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_script_current_script_CALL_INSTANCE));
  CMOCK_script_current_script_CALL_INSTANCE* cmock_call_instance = (CMOCK_script_current_script_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.script_current_script_CallInstance = CMock_Guts_MemChain(Mock.script_current_script_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_script_current_script(cmock_call_instance, out, out_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

