/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDISPLAY_H
#define _MOCKDISPLAY_H

#include "unity.h"
#include "display.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockdisplay_Init(void);
void Mockdisplay_Destroy(void);
void Mockdisplay_Verify(void);




#define display_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("display_init requires _Expect (not AndReturn)");
#define display_init_Expect() display_init_CMockExpect(__LINE__)
void display_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define display_shutdown_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("display_shutdown requires _Expect (not AndReturn)");
#define display_shutdown_Expect() display_shutdown_CMockExpect(__LINE__)
void display_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define display_get_main_bg_Expect(layer) TEST_FAIL_MESSAGE("display_get_main_bg requires _ExpectAndReturn");
#define display_get_main_bg_ExpectAndReturn(layer, cmock_retval) display_get_main_bg_CMockExpectAndReturn(__LINE__, layer, cmock_retval)
void display_get_main_bg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, MainDisplayBgLayer layer, int cmock_to_return);
#define display_get_sub_bg_Expect(layer) TEST_FAIL_MESSAGE("display_get_sub_bg requires _ExpectAndReturn");
#define display_get_sub_bg_ExpectAndReturn(layer, cmock_retval) display_get_sub_bg_CMockExpectAndReturn(__LINE__, layer, cmock_retval)
void display_get_sub_bg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SubDisplayBgLayer layer, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
