/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdisplay.h"

static const char* CMockString_display_get_main_bg = "display_get_main_bg";
static const char* CMockString_display_get_sub_bg = "display_get_sub_bg";
static const char* CMockString_display_init = "display_init";
static const char* CMockString_display_shutdown = "display_shutdown";
static const char* CMockString_layer = "layer";

typedef struct _CMOCK_display_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_display_init_CALL_INSTANCE;

typedef struct _CMOCK_display_shutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_display_shutdown_CALL_INSTANCE;

typedef struct _CMOCK_display_get_main_bg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  MainDisplayBgLayer Expected_layer;

} CMOCK_display_get_main_bg_CALL_INSTANCE;

typedef struct _CMOCK_display_get_sub_bg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  SubDisplayBgLayer Expected_layer;

} CMOCK_display_get_sub_bg_CALL_INSTANCE;

static struct MockdisplayInstance
{
  CMOCK_MEM_INDEX_TYPE display_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE display_shutdown_CallInstance;
  CMOCK_MEM_INDEX_TYPE display_get_main_bg_CallInstance;
  CMOCK_MEM_INDEX_TYPE display_get_sub_bg_CallInstance;
} Mock;


void Mockdisplay_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.display_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_display_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.display_shutdown_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_display_shutdown);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.display_get_main_bg_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_display_get_main_bg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.display_get_sub_bg_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_display_get_sub_bg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockdisplay_Init(void)
{
  Mockdisplay_Destroy();
}

void Mockdisplay_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void display_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_display_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_display_init);
  cmock_call_instance = (CMOCK_display_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.display_init_CallInstance);
  Mock.display_init_CallInstance = CMock_Guts_MemNext(Mock.display_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void display_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_display_init_CALL_INSTANCE));
  CMOCK_display_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_display_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.display_init_CallInstance = CMock_Guts_MemChain(Mock.display_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void display_shutdown(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_display_shutdown_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_display_shutdown);
  cmock_call_instance = (CMOCK_display_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.display_shutdown_CallInstance);
  Mock.display_shutdown_CallInstance = CMock_Guts_MemNext(Mock.display_shutdown_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void display_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_display_shutdown_CALL_INSTANCE));
  CMOCK_display_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_display_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.display_shutdown_CallInstance = CMock_Guts_MemChain(Mock.display_shutdown_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

int display_get_main_bg(MainDisplayBgLayer layer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_display_get_main_bg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_display_get_main_bg);
  cmock_call_instance = (CMOCK_display_get_main_bg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.display_get_main_bg_CallInstance);
  Mock.display_get_main_bg_CallInstance = CMock_Guts_MemNext(Mock.display_get_main_bg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_display_get_main_bg,CMockString_layer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_layer, &layer, sizeof(MainDisplayBgLayer), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_display_get_main_bg(CMOCK_display_get_main_bg_CALL_INSTANCE* cmock_call_instance, MainDisplayBgLayer layer);
void CMockExpectParameters_display_get_main_bg(CMOCK_display_get_main_bg_CALL_INSTANCE* cmock_call_instance, MainDisplayBgLayer layer)
{
  memcpy((void*)(&cmock_call_instance->Expected_layer), (const void*)(&layer),
         sizeof(MainDisplayBgLayer[sizeof(layer) == sizeof(MainDisplayBgLayer) ? 1 : -1])); /* add MainDisplayBgLayer to :treat_as_array if this causes an error */
}

void display_get_main_bg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, MainDisplayBgLayer layer, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_display_get_main_bg_CALL_INSTANCE));
  CMOCK_display_get_main_bg_CALL_INSTANCE* cmock_call_instance = (CMOCK_display_get_main_bg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.display_get_main_bg_CallInstance = CMock_Guts_MemChain(Mock.display_get_main_bg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_display_get_main_bg(cmock_call_instance, layer);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int display_get_sub_bg(SubDisplayBgLayer layer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_display_get_sub_bg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_display_get_sub_bg);
  cmock_call_instance = (CMOCK_display_get_sub_bg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.display_get_sub_bg_CallInstance);
  Mock.display_get_sub_bg_CallInstance = CMock_Guts_MemNext(Mock.display_get_sub_bg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_display_get_sub_bg,CMockString_layer);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_layer, &layer, sizeof(SubDisplayBgLayer), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_display_get_sub_bg(CMOCK_display_get_sub_bg_CALL_INSTANCE* cmock_call_instance, SubDisplayBgLayer layer);
void CMockExpectParameters_display_get_sub_bg(CMOCK_display_get_sub_bg_CALL_INSTANCE* cmock_call_instance, SubDisplayBgLayer layer)
{
  memcpy((void*)(&cmock_call_instance->Expected_layer), (const void*)(&layer),
         sizeof(SubDisplayBgLayer[sizeof(layer) == sizeof(SubDisplayBgLayer) ? 1 : -1])); /* add SubDisplayBgLayer to :treat_as_array if this causes an error */
}

void display_get_sub_bg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SubDisplayBgLayer layer, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_display_get_sub_bg_CALL_INSTANCE));
  CMOCK_display_get_sub_bg_CALL_INSTANCE* cmock_call_instance = (CMOCK_display_get_sub_bg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.display_get_sub_bg_CallInstance = CMock_Guts_MemChain(Mock.display_get_sub_bg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_display_get_sub_bg(cmock_call_instance, layer);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

