/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTEXT_H
#define _MOCKTEXT_H

#include "unity.h"
#include "text.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocktext_Init(void);
void Mocktext_Destroy(void);
void Mocktext_Verify(void);




#define text_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("text_init requires _Expect (not AndReturn)");
#define text_init_Expect() text_init_CMockExpect(__LINE__)
void text_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define text_clear_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("text_clear requires _Expect (not AndReturn)");
#define text_clear_Expect() text_clear_CMockExpect(__LINE__)
void text_clear_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define text_begin_dialogue_ExpectAndReturn(speaker, text, cmock_retval) TEST_FAIL_MESSAGE("text_begin_dialogue requires _Expect (not AndReturn)");
#define text_begin_dialogue_Expect(speaker, text) text_begin_dialogue_CMockExpect(__LINE__, speaker, text)
void text_begin_dialogue_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* speaker, const char* text);
#define text_begin_narration_ExpectAndReturn(text, cmock_retval) TEST_FAIL_MESSAGE("text_begin_narration requires _Expect (not AndReturn)");
#define text_begin_narration_Expect(text) text_begin_narration_CMockExpect(__LINE__, text)
void text_begin_narration_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* text);
#define text_update_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("text_update requires _Expect (not AndReturn)");
#define text_update_Expect() text_update_CMockExpect(__LINE__)
void text_update_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define text_finish_immediately_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("text_finish_immediately requires _Expect (not AndReturn)");
#define text_finish_immediately_Expect() text_finish_immediately_CMockExpect(__LINE__)
void text_finish_immediately_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define text_is_finished_Expect() TEST_FAIL_MESSAGE("text_is_finished requires _ExpectAndReturn");
#define text_is_finished_ExpectAndReturn(cmock_retval) text_is_finished_CMockExpectAndReturn(__LINE__, cmock_retval)
void text_is_finished_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define text_debug_set_ExpectAndReturn(text, cmock_retval) TEST_FAIL_MESSAGE("text_debug_set requires _Expect (not AndReturn)");
#define text_debug_set_Expect(text) text_debug_set_CMockExpect(__LINE__, text)
void text_debug_set_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* text);
#define text_debug_clear_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("text_debug_clear requires _Expect (not AndReturn)");
#define text_debug_clear_Expect() text_debug_clear_CMockExpect(__LINE__)
void text_debug_clear_CMockExpect(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
